FROM node:14

RUN apk add --no-cache \
  python3 \
  make \
  g++

WORKDIR /app

ENV NODE_ENV development
COPY package*.json /app/
RUN npm install

COPY . /app

EXPOSE 8888

CMD ["npm", "run", "dev"]
