FROM node:14

RUN apt-get update && apt-get install -y \
  build-essential \
  python3

WORKDIR /app

ENV NODE_ENV development
COPY package*.json /app/
RUN npm install

COPY . /app

EXPOSE 8888

CMD ["npm", "run", "dev"]
