services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.server
#    ports:
#      - "8888:8888"
#    volumes:
#      - .:/app
#      - /app/node_modules
#    environment:
#      - NODE_ENV=development
#    depends_on:
#      - mongo

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
